{{- if .Values.p2pVpn.isBootstrapPeer }}
apiVersion: v1
kind: Service
metadata:
  name: p2p-vpn-p2p
  labels:
    app: p2p-vpn
spec:
  type: LoadBalancer
  selector:
    app: p2p-vpn
  ports:
    - name: p2p-tcp
      port: {{ .Values.p2pVpn.p2pPort }}
      targetPort: p2p-tcp
      protocol: TCP
    - name: p2p-udp
      port: {{ .Values.p2pVpn.p2pPort }}
      targetPort: p2p-udp
      protocol: UDP
{{- end }}
