{{- if .Values.p2pVpn.generateDataKey }}
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: p2p-vpn-gen
  namespace: {{ $.Release.Namespace }}
spec:
  length: 32
  digits: 10
  symbols: 0
  noUpper: true
  allowRepeat: true
  secretKeys:
    - datakey

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.p2pVpn.dataKeySecretName }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "0"
  target:
    name: {{ .Values.p2pVpn.dataKeySecretName }}
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        {{ .Values.p2pVpn.dataKeySecretKey | default "token" }}: '{{ "{{ .datakey | sha256sum }}" }}'
  dataFrom:
    - sourceRef:
        generatorRef:
          name: p2p-vpn-gen
          kind: Password
          apiVersion: generators.external-secrets.io/v1alpha1
{{- end }}
