apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openldap-ha
  namespace: {{ .Values.argoNamespace }}
spec:
  project: default
  source:
    repoURL: https://jp-gouin.github.io/helm-openldap/
    chart: openldap-stack-ha
    targetRevision: 4.3.3
    helm:
      values: |
        global:
          ldapDomain: "{{ .Values.cluster.name }}.loa.internal"
          adminPassword: "devPasswordForAMoment!"

        # 1. Pod Level Security
        podSecurityContext:
          enabled: true
          fsGroup: 1000
          seccompProfile:
            type: RuntimeDefault

        # 2. Container Level Security (The "Restricted" Standard)
        containerSecurityContext:
          enabled: true
          runAsUser: 1001
          runAsGroup: 1001
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL

        command: ["/opt/bitnami/openldap/sbin/slapd"]
        args: 
          - "-d"
          - "3"
          - "-f"
          - "/opt/bitnami/openldap/etc/slapd.conf"
          - "-h"
          - "ldap://:1389 ldaps://:1636"

        # 3. Handle Read-Only Filesystem Requirements
        # When readOnlyRootFilesystem is true, we must mount a tmp volume
        # because OpenLDAP tries to write temporary lock files.
        extraVolumes:
          - name: ldap-temp
            emptyDir: {}
          - name: custom-config
            configMap:
              name: openldap-slapd
        extraVolumeMounts:
          - name: ldap-temp
            mountPath: /tmp
          - name: ldap-temp
            mountPath: /opt/bitnami/openldap/var/run
          - name: custom-config
            mountPath: /opt/bitnami/openldap/etc/slapd.conf
            subPath: slapd.conf

        # --- phpLDAPadmin Configuration ---
        phpldapadmin:
          enabled: true
          # Force the container to run as non-root (usually 1001 or 33 depending on image)
          # Bitnami images use 1001.
          containerSecurityContext:
            runAsUser: 1001
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities: { drop: ["ALL"] }

          # Apache/PHP needs these writable areas to start in ReadOnly mode
          extraVolumes:
            - name: pla-temp
              emptyDir: {}
          extraVolumeMounts:
            - name: pla-temp
              mountPath: /tmp
            - name: pla-temp
              mountPath: /opt/bitnami/phpldapadmin/tmp
            - name: pla-temp
              mountPath: /opt/bitnami/apache/var/run
            - name: pla-temp
              mountPath: /opt/bitnami/apache/logs

        # --- LTB-Passwd (Self Service Password) Configuration ---
        ltb-passwd:
          enabled: true
          containerSecurityContext:
            runAsUser: 1001
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities: { drop: ["ALL"] }

          # PHP needs to write session data and apache PIDs
          extraVolumes:
            - name: ltb-temp
              emptyDir: {}
          extraVolumeMounts:
            - name: ltb-temp
              mountPath: /tmp
            - name: ltb-temp
              mountPath: /opt/bitnami/apache/var/run
            - name: ltb-temp
              mountPath: /opt/bitnami/apache/logs
            # Specific to LTB/PHP sessions
            - name: ltb-temp
              mountPath: /var/lib/php/sessions
  destination:
    server: https://kubernetes.default.svc
    namespace: openldap
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true