apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openldap-ha
  namespace: {{ .Values.argoNamespace }}
spec:
  project: default
  source:
    repoURL: https://jp-gouin.github.io/helm-openldap/
    chart: openldap-stack-ha
    targetRevision: 4.x.x
    helm:
      values: |
        global:
          ldapDomain: "{{ .Values.cluster.name }}.loa.internal"
          adminPassword: "devPasswordForAMoment!"

        # 1. Pod Level Security
        podSecurityContext:
          enabled: true
          fsGroup: 1000
          seccompProfile:
            type: RuntimeDefault

        # 2. Container Level Security (The "Restricted" Standard)
        containerSecurityContext:
          enabled: true
          runAsUser: 1002
          runAsGroup: 1002
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL

        # 3. Handle Read-Only Filesystem Requirements
        # When readOnlyRootFilesystem is true, we must mount a tmp volume
        # because OpenLDAP tries to write temporary lock files.
        extraVolumes:
          - name: temp-volume
            emptyDir: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: openldap
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true