apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg-operator
  namespace: {{ .Values.argoNamespace }}
spec:
  project: default
  source:
    repoURL: 'https://cloudnative-pg.github.io/charts'
    chart: cloudnative-pg
    # Using a specific version is best practice for GitOps stability.
    # Check ArtifactHub for the latest: https://artifacthub.io/packages/helm/cloudnative-pg/cloudnative-pg
    targetRevision: 0.27.0
    helm:
      values: |
        # The operator is secure by default (readOnlyRootFilesystem: true, etc.)
        # so we generally do not need to override security contexts here 
        # unless you have very specific SCC requirements (e.g. OpenShift).
        config:
          secretManager:
            # Tells CNPG to explicitly use cert-manager for webhook certs
            type: cert-manager
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cnpg-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true