apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: federation-externaldns
  namespace: {{ .Values.argoNamespace }}
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    chart: external-dns
    targetRevision: 1.21.1
    helm:
      valuesObject:
        provider:
          name: cloudflare

        env:
          - name: CF_API_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ .Values.externaldns.apiKeySecret }}
                key: {{ .Values.externaldns.apiKeySecretKey }}

        # The "Secret Sauce" to prevent clusters from fighting
        policy: upsert-only
        registry: "txt"
        txtOwnerId: {{ .Values.cluster.federation.name }}

        # Tell ExternalDNS to watch the Gateway API
        sources:
          - gateway-tlsroute
          - gateway

        # TODO only do for federation services gateways
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: {{ .Values.externaldns.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    # pull from internet
    managedNamespaceMetadata:
      labels:
        zarf.dev/agent: "ignore"