apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: {{ .Values.argoNamespace }}
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: keycloak
    targetRevision: 16.x.x
    helm:
      values: |
        replicaCount: 2
        mode: ha
        
        # --- Security Context for Restricted Namespace ---
        
        # 1. Pod Level Security
        # We enforce the user ID and filesystem group to match Bitnami's non-root user (1001).
        # We also set the seccomp profile, which is mandatory for Restricted PSS.
        podSecurityContext:
          enabled: true
          fsGroup: 1001
          runAsUser: 1001
          runAsGroup: 1001
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault

        # 2. Container Level Security
        # We drop all capabilities and prevent privilege escalation.
        containerSecurityContext:
          enabled: true
          runAsNonRoot: true
          runAsUser: 1001
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          # readOnlyRootFilesystem: true 
          # Note: If you enable readOnlyRootFilesystem, you must mount 
          # extra emptyDir volumes for /tmp and /opt/bitnami/keycloak/logs

        # --- Application Logic (Previous Config) ---

        postgresql:
          enabled: false

        extraEnvVars:
          - name: KC_DB
            value: app
          - name: KC_DB_URL_DATABASE
            value: "app"
          - name: KC_DB_URL_HOST
            valueFrom:
              secretKeyRef:
                name: keycloak-pgedge-creds
                key: endpoint
          - name: KC_DB_URL_PORT
            valueFrom:
              secretKeyRef:
                name: keycloak-pgedge-creds
                key: port
          # JDBC Cert Auth string
          - name: KC_DB_URL_PROPERTIES
            value: "?sslmode=verify-full&sslcert=/etc/x509/db-client/tls.crt&sslkey=/etc/x509/db-client/tls.key&sslrootcert=/etc/x509/db-client/ca.crt"
          - name: KC_DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: keycloak-pgedge-creds
                key: username

        extraVolumeMounts:
          - name: https-certs
            mountPath: /etc/x509/https
            readOnly: true
          - name: db-client-certs
            mountPath: /etc/x509/db-client
            readOnly: true

        extraVolumes:
          - name: https-certs
            csi:
              driver: csi.cert-manager.io
              readOnly: true
              volumeAttributes:
                  csi.cert-manager.io/issuer-name: "vault-issuer"
                  csi.cert-manager.io/issuer-kind: "ClusterIssuer"
                  csi.cert-manager.io/dns-names: "idp.{{ .Values.cluster.name }}.loa.internal"
          - name: db-client-certs
            secret:
              secretName: app-client-cert
              defaultMode: 0400 

        tls:
          enabled: true
          autoGenerated: false
          usePemCerts: true

        command: ["/opt/bitnami/scripts/keycloak/entrypoint.sh"]
        args:
          - start
          - --https-certificate-file=/etc/x509/https/tls.crt
          - --https-certificate-key-file=/etc/x509/https/tls.key
        
        service:
          type: ClusterIP
          ports:
            http: 80
            https: 443

        ingress:
          enabled: true
          hostname: idp.{{ .Values.cluster.name }}.loa.internal
          annotations:
            nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"

  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true