apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: {{ .Values.argoNamespace }}
spec:
  project: default
  source:
    # CloudPirates hosts their charts in an OCI registry
    repoURL: registry-1.docker.io/cloudpirates
    chart: keycloak
    targetRevision: 0.11.3 # Check ArtifactHub for the latest version
    helm:
      values: |
        replicaCount: 2
        
        # 2. Database (Disable internal, we use Crossplane/pgEdge)
        postgres:
          enabled: false

        database:
          type: postgres
          host: pgedge-cluster-{{ .Values.cluster.name }}-data-rw.pgedge.svc.cluster.local
          port: "5432"
          schema: app
          name: app
          username: app
          jdbcParams: "sslmode=verify-full&sslcert=/etc/x509/db-client/tls.crt&sslkey=/tmp/tls.fixed.key&sslrootcert=/etc/x509/db-client/ca.crt"
        
        # 3. Environment Variables (The "Magic Glue")
        # We inject the DB credentials and the JDBC Cert-Auth string here.
        env:
          - name: KC_DB
            value: app
          - name: KC_DB_URL_DATABASE
            value: "app"
          - name: KC_DB_URL_HOST
            value: "pgedge-cluster-{{ .Values.cluster.name }}-data-rw.pgedge.svc.cluster.local"
          - name: KC_DB_URL_PORT
            value: 5432
          - name: KC_DB_USERNAME
            value: app
          # Construct the JDBC URL parameters for Mutual TLS
          - name: KC_DB_URL_PROPERTIES
            value: "sslmode=verify-full&sslcert=/etc/x509/db-client/tls.crt&sslkey=/tmp/tls.fixed.key&sslrootcert=/etc/x509/db-client/ca.crt"
          # Vital for functioning behind an Ingress
          # - name: KC_PROXY
          #   value: "edge" 
          # - name: KC_HOSTNAME_STRICT
          #   value: "false"

        tls:
          enabled: true
          existingSecret: keycloak-ingress-tls
          usePem: true
          certManager:
            enabled: true
            issuerRef:
              name: pki-bootstrap
              kind: ClusterIssuer

        # 4. Volumes (CSI & Secrets)
        extraVolumes:
          # DB Client Certs (via Crossplane/Manual Secret)
          - name: db-client-certs
            secret:
              secretName: pgadmin-app-client-cert
              defaultMode: 0400
          - name: tmp-volume
            emptyDir: {}

        extraVolumeMounts:
          - name: db-client-certs
            mountPath: /etc/x509/db-client
            readOnly: true
          - mountPath: /tmp
            name: tmp-volume
            
        extraInitContainers:
          - name: pkcs1-to-pkcs8
            securityContext:
              runAsNonRoot: true
              allowPrivilegeEscalation: false
              capabilities:
                drop: ["ALL"]
            image: alpine/openssl:3.5.4
            command: 
              - openssl
              - pkcs8
              - -topk8
              - -inform
              - PEM
              - -outform
              - PEM
              - -in
              - /etc/x509/db-client/tls.key
              - -out
              - /tmp/tls.fixed.key
              - -nocrypt
            volumeMounts:
              - name: tmp-volume
                mountPath: /tmp
              - name: db-client-certs
                mountPath: /etc/x509/db-client
                readOnly: true

        # 6. Security Context (Restricted Namespace Compliance)
        # Pod-level security
        podSecurityContext:
          runAsNonRoot: true
          runAsUser: 1000       # Keycloak official image UID
          runAsGroup: 1000
          fsGroup: 1000         # Ensures we can read the mounted certs
          seccompProfile:
            type: RuntimeDefault

        # Container-level security
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]

        # 7. Networking
        service:
          port: 443
          targetPort: 8443

        ingress:
          enabled: true
          className: nginx
          rules:
            - host: idp.{{ .Values.cluster.name }}.loa.internal
              paths:
                - path: /
                  pathType: Prefix
          annotations:
            nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        
        keycloak:
          production: true

  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true