apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: {{ .Values.argoNamespace }}
spec:
  project: default
  source:
    # CloudPirates hosts their charts in an OCI registry
    repoURL: registry-1.docker.io/cloudpirates
    chart: keycloak
    targetRevision: 0.11.3 # Check ArtifactHub for the latest version
    helm:
      values: |
        # 1. Image & Replicas
        replicaCount: 2
        image:
          tag: 26.0 # Explicitly pin the Keycloak version
          pullPolicy: IfNotPresent
        
        # 2. Database (Disable internal, we use Crossplane/pgEdge)
        postgresql:
          enabled: false
        
        # 3. Environment Variables (The "Magic Glue")
        # We inject the DB credentials and the JDBC Cert-Auth string here.
        env:
          - name: KC_DB
            value: app
          - name: KC_DB_URL_DATABASE
            value: "app"
          - name: KC_DB_URL_HOST
            value: "pgedge-cluster-{{ .Values.cluster.name }}-data-rw.pgedge.svc.cluster.local"
          - name: KC_DB_URL_PORT
            value: 5432
          - name: KC_DB_USERNAME
            value: app
          # Construct the JDBC URL parameters for Mutual TLS
          - name: KC_DB_URL_PROPERTIES
            value: "?sslmode=verify-full&sslcert=/etc/x509/db-client/tls.crt&sslkey=/etc/x509/db-client/tls.key&sslrootcert=/etc/x509/db-client/ca.crt"
          # Vital for functioning behind an Ingress
          # - name: KC_PROXY
          #   value: "edge" 
          # - name: KC_HOSTNAME_STRICT
          #   value: "false"

        # 4. Volumes (CSI & Secrets)
        extraVolumes:
          # Server HTTPS Certs (via Cert-Manager CSI)
          - name: https-certs
            csi:
              driver: csi.cert-manager.io
              readOnly: true
              volumeAttributes:
                  csi.cert-manager.io/issuer-name: "pki-bootstrap"
                  csi.cert-manager.io/issuer-kind: "ClusterIssuer"
                  csi.cert-manager.io/dns-names: "idp.{{ .Values.cluster.name }}.loa.internal"
          
          # DB Client Certs (via Crossplane/Manual Secret)
          - name: db-client-certs
            secret:
              secretName: app-client-cert
              defaultMode: 0400

        extraVolumeMounts:
          - name: https-certs
            mountPath: /etc/x509/https
            readOnly: true
          - name: db-client-certs
            mountPath: /etc/x509/db-client
            readOnly: true

        # 6. Security Context (Restricted Namespace Compliance)
        # Pod-level security
        podSecurityContext:
          runAsNonRoot: true
          runAsUser: 1000       # Keycloak official image UID
          runAsGroup: 1000
          fsGroup: 1000         # Ensures we can read the mounted certs
          seccompProfile:
            type: RuntimeDefault

        # Container-level security
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]

        # 7. Networking
        service:
          port: 443
          targetPort: 8443

        ingress:
          enabled: true
          className: nginx
          rules:
            - host: idp.{{ .Values.cluster.name }}.loa.internal
              paths:
                - path: /
                  pathType: Prefix
          annotations:
            nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"

  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true