apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netbird-controller
  namespace: {{ .Values.argoNamespace }}
spec:
  project: default
  source:
    repoURL: 'https://netbirdio.github.io/helms'
    targetRevision: 1.8.0 # Latest release
    chart: netbird
    helm:
      values: |
        management:
          containerPort: 443
          service:
            port: 443
            name: https
          podCommand:
            args:
              - --port=443
              - --log-file=console
              - --log-level=info
              - --disable-anonymous-metrics=false
              - --dns-domain={{ include "netbird-external-url" . }}
          podSecurityContext:
            runAsNonRoot: true
            runAsUser: 1002
            runAsGroup: 1002
            fsGroup: 1002
            seccompProfile:
              type: RuntimeDefault
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true 
            capabilities:
              drop:
                - ALL
          livenessProbe:
            tcpSocket:
              port: https
          readinessProbe:
            tcpSocket:
              port: https
          configmap: |-
              {
                "Stuns": [
                  {
                    "Proto": "udp",
                    "URI": "{{ .STUN_SERVER }}",
                    "Username": "",
                    "Password": null
                  }
                ],
                "TURNConfig": {
                  "Turns": [
                    {
                      "Proto": "udp",
                      "URI": "{{ .TURN_SERVER }}",
                      "Username": "{{ .TURN_SERVER_USER }}",
                      "Password": "{{ .TURN_SERVER_PASSWORD }}"
                    }
                  ],
                  "CredentialsTTL": "12h",
                  "Secret": "secret",
                  "TimeBasedCredentials": false
                },
                "Relay": {
                  "Addresses": [
                    "rels://netbird.example.com:443/relay"
                  ],
                  "CredentialsTTL": "24h",
                  "Secret": "{{ .RELAY_PASSWORD }}"
                },
                "Signal": {
                  "Proto": "https",
                  "URI": "netbird.example.com:443",
                  "Username": "",
                  "Password": null
                },
                "ReverseProxy": {
                  "TrustedHTTPProxies": [],
                  "TrustedHTTPProxiesCount": 0,
                  "TrustedPeers": [
                    "0.0.0.0/0"
                  ]
                },
                "Datadir": "",
                "DataStoreEncryptionKey": "{{ .DATASTORE_ENCRYPTION_KEY }}",
                "StoreConfig": {
                  "Engine": "sqlite"
                },
                "HttpConfig": {
                  "Address": "0.0.0.0:33073",
                  "AuthIssuer": "https://example.okta.com",
                  "AuthAudience": "{{ .IDP_CLIENT_ID }}",
                  "AuthKeysLocation": "https://example.okta.com/oauth2/v1/keys",
                  "AuthUserIDClaim": "",
                  "IdpSignKeyRefreshEnabled": false,
                  "OIDCConfigEndpoint": "https://example.okta.com/.well-known/openid-configuration"
                },
                "IdpManagerConfig": {
                  "ManagerType": "okta",
                  "ClientConfig": {
                    "Issuer": "https://example.okta.com",
                    "TokenEndpoint": "https://example.okta.com/oauth2/v1/token",
                    "ClientID": "{{ .IDP_CLIENT_ID }}",
                    "ClientSecret": "",
                    "GrantType": "client_credentials"
                  },
                  "ExtraConfig": {
                    "ApiToken": "{{ .OKTA_API_TOKEN }}"
                  },
                  "Auth0ClientCredentials": null,
                  "AzureClientCredentials": null,
                  "KeycloakClientCredentials": null,
                  "ZitadelClientCredentials": null
                },
                "DeviceAuthorizationFlow": {
                  "Provider": "hosted",
                  "ProviderConfig": {
                    "Audience": "{{ .IDP_NATIVEAPP_CLIENT_ID }}",
                    "AuthorizationEndpoint": "",
                    "Domain": "",
                    "ClientID": "nativeclientid",
                    "ClientSecret": "",
                    "TokenEndpoint": "https://example.okta.com/oauth2/v1/token",
                    "DeviceAuthEndpoint": "https://example.okta.com/oauth2/v1/device/authorize",
                    "Scope": "openid email groups",
                    "UseIDToken": true,
                    "RedirectURLs": null
                  }
                },
                "PKCEAuthorizationFlow": {
                  "ProviderConfig": {
                    "Audience": "{{ .IDP_CLIENT_ID }}",
                    "ClientID": "{{ .IDP_CLIENT_ID }}",
                    "ClientSecret": "",
                    "Domain": "",
                    "AuthorizationEndpoint": "https://example.okta.com/oauth2/v1/authorize",
                    "TokenEndpoint": "https://example.okta.com/oauth2/v1/token",
                    "Scope": "openid profile email groups",
                    "RedirectURLs": [
                      "http://localhost:53000"
                    ],
                    "UseIDToken": true
                  }
                }
              }

            envFromSecret:
              STUN_SERVER: netbird/stunServer
              TURN_SERVER: netbird/turnServer
              TURN_SERVER_USER: netbird/turnServerUser
              TURN_SERVER_PASSWORD: netbird/turnServerPassword
              RELAY_PASSWORD: netbird/relayPassword
              DATASTORE_ENCRYPTION_KEY: netbird/datastoreEncryptionKey
              IDP_CLIENT_ID: netbird/idpClientID
              OKTA_API_TOKEN: netbird/oktaApiToken
              IDP_NATIVEAPP_CLIENT_ID: netbird/idpNativeAppClientID`
        dashboard:
          podSecurityContext:
            runAsNonRoot: true
            runAsUser: 1003
            runAsGroup: 1003
            fsGroup: 1003
            seccompProfile:
              type: RuntimeDefault
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true 
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - mountPath: /tmp
              name: tmp-volume
          volumes:
            - name: tmp-volume
              emptyDir: {}
        relay:
          podSecurityContext:
            runAsNonRoot: true
            runAsUser: 1003
            runAsGroup: 1003
            fsGroup: 1003
            seccompProfile:
              type: RuntimeDefault
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true 
            capabilities:
              drop:
                - ALL
        signal:
          podSecurityContext:
            runAsNonRoot: true
            runAsUser: 1003
            runAsGroup: 1003
            fsGroup: 1003
            seccompProfile:
              type: RuntimeDefault
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true 
            capabilities:
              drop:
                - ALL
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: {{ .Values.netbird.controller.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    # pull from internet
    managedNamespaceMetadata:
      labels:
        zarf.dev/agent: "ignore"