apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netbird-controller
  namespace: {{ .Values.argoNamespace }}
spec:
  project: default
  source:
    repoURL: 'https://netbirdio.github.io/helms'
    targetRevision: 1.8.0 # Latest release
    chart: netbird
    helm:
      values: |
        dashboard:
          podSecurityContext:
            runAsNonRoot: true
            runAsUser: 1003
            runAsGroup: 1003
            fsGroup: 1003
            seccompProfile:
              type: RuntimeDefault
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true 
            capabilities:
              drop:
                - ALL
        management:
          podSecurityContext:
            runAsNonRoot: true
            runAsUser: 1002
            runAsGroup: 1002
            fsGroup: 1002
            seccompProfile:
              type: RuntimeDefault
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true 
            capabilities:
              drop:
                - ALL
        relay:
          podSecurityContext:
            runAsNonRoot: true
            runAsUser: 1003
            runAsGroup: 1003
            fsGroup: 1003
            seccompProfile:
              type: RuntimeDefault
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true 
            capabilities:
              drop:
                - ALL
        signal:
          podSecurityContext:
            runAsNonRoot: true
            runAsUser: 1003
            runAsGroup: 1003
            fsGroup: 1003
            seccompProfile:
              type: RuntimeDefault
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true 
            capabilities:
              drop:
                - ALL
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: {{ .Values.netbird.controllerNamespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    # pull from internet
    managedNamespaceMetadata:
      labels:
        zarf.dev/agent: "ignore"