apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: federation-p2p-vpn
  namespace: {{ .Values.argoNamespace }}
spec:
  project: default
  source:
    repoURL: https://github.com/kevinpthorne/libraryofalexandria.git
    path: apps/p2p-vpn-bgp
    targetRevision: HEAD
    helm:
      releaseName: federation-p2p-vpn
      valuesObject:
        p2pVpn:
          generateDataKey: true # Generate the data key via ExternalSecrets in THIS cluster! Remove after bootstrapping
          address: {{ .Values.cluster.p2pVpnAddress }}
          isBootstrapPeer: {{ .Values.cluster.federationBootstrap.isBootstrapPeer }}
          bootstrapPeers:
            {{- if .Values.cluster.federationBootstrap.peers }}
            {{- range .Values.cluster.federationBootstrap.peers }}
            - {{ . | quote }}
            {{- end }}
            {{- else }}
            []
            {{- end }}
        bgp:
          localAS: {{ .Values.cluster.localAS }}
          routerId: {{ .Values.cluster.federationBorderRouterIp }}
          localCIDRs:
            - {{ .Values.cluster.serviceCidr }}
            - {{ .Values.cluster.clusterCidr }}
          vpnPeers:
            {{- if .Values.cluster.vpnPeers }}
            {{- range .Values.cluster.vpnPeers }}
            - {{ . | quote }}
            {{- end }}
            {{- else }}
            []
            {{- end }}
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
