apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pgedge-restricted
  namespace: {{ .Values.argoNamespace }}
spec:
  project: default
  source:
    repoURL: 'https://github.com/kevinpthorne/pgedge-helm'
    targetRevision: main
    path: .
    helm:
      # We override the values to enforce a restricted security context
      values: |
        pgEdge:
          appName: pgedge-cluster
          enableSuperuserAccess: true
          nodes:
            - name: {{ .Values.cluster.name }}-data
              hostname: pgedge-cluster-{{ .Values.cluster.name }}-data-rw
              clusterSpec:
                instances: {{ tpl .Values.pgedge.instances . }}
                # CloudNativePG Security Context Injection
                image:
                  podSecurityContext:
                    runAsNonRoot: true
                    runAsUser: 26        # Standard Postgres UID
                    runAsGroup: 26       # Standard Postgres GID
                    fsGroup: 26
                    seccompProfile:
                      type: RuntimeDefault
                  securityContext:
                    allowPrivilegeEscalation: false
                    readOnlyRootFilesystem: true
                    capabilities:
                      drop:
                        - ALL
                # SPOCK MULTI-MASTER CONFIG (Required)
                postgresql:
                  parameters:
                    wal_level: "logical"
                    max_worker_processes: "20"
                    max_replication_slots: "20"
                    max_wal_senders: "20"
                    track_commit_timestamp: "on"
                # Required for readOnlyRootFilesystem to work (Postgres needs tmp write access)
                storage:
                  size: 1Gi
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: pgedge
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true