apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pgedge-restricted
  namespace: {{ .Values.argoNamespace }}
spec:
  project: default
  source:
    repoURL: 'https://github.com/kevinpthorne/pgedge-helm'
    targetRevision: main
    path: .
    helm:
      # We override the values to enforce a restricted security context
      values: |
        pgEdge:
          appName: {{ .Values.pgedge.appName }}
          nodes:
            - name: {{ .Values.cluster.name }}-data
              hostname: {{ .Values.pgedge.appName }}-{{ .Values.cluster.name }}-data-rw
              clusterSpec:
                instances: {{ tpl .Values.pgedge.instances . }}
                imagePullPolicy: IfNotPresent
                certificates:
                  serverTLSSecret: pgedge-{{ .Values.pgedge.appName }}-server-cert
                  serverCASecret: pgedge-{{ .Values.pgedge.appName }}-server-cert
                  clientCASecret: pgedge-{{ .Values.pgedge.appName }}-client-ca-key-pair
                  replicationTLSSecret: streaming-replica-client-cert
                # CloudNativePG Security Context Injection
                image:
                  podSecurityContext:
                    runAsNonRoot: true
                    runAsUser: 26        # Standard Postgres UID
                    runAsGroup: 26       # Standard Postgres GID
                    fsGroup: 26
                    seccompProfile:
                      type: RuntimeDefault
                  securityContext:
                    allowPrivilegeEscalation: false
                    readOnlyRootFilesystem: true
                    capabilities:
                      drop:
                        - ALL
                # SPOCK MULTI-MASTER CONFIG (Required)
                postgresql:
                {{- if gt (int (tpl .Values.pgedge.instances .)) 1 -}}
                  synchronous:
                    method: any
                    number: 1
                    dataDurability: required
                {{- end -}}
                  parameters:
                    wal_level: "logical"
                    max_worker_processes: "20"
                    max_replication_slots: "20"
                    max_wal_senders: "20"
                    track_commit_timestamp: "on"
                  pg_hba:
                    - hostssl all all all cert  # let's let cilium network policies gatekeep access
                    - hostssl all streaming_replica all cert map=cnpg_streaming_replica  # comes from pgedge-helm
                # Required for readOnlyRootFilesystem to work (Postgres needs tmp write access)
                storage:
                  size: 1Gi
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: {{ .Values.pgedge.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true