apiVersion: auth.loa.kevinpthorne.com/v1alpha1
kind: SecretStore
metadata:
  name: pgedge-secret-store-claim
spec:
  targetNamespace: pgedge
  replicatorSA: secret-replicator-sa
  replicatorNamespace: external-secrets