apiVersion: auth.loa.kevinpthorne.com/v1alpha1
kind: SecretStore
metadata:
  name: pgedge-secret-store-claim
  namespace: default # force ArgoCD to not make this namespaced...maybe
spec:
  targetNamespace: pgedge
  replicatorSA: secret-replicator-sa
  replicatorNamespace: external-secrets