apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keydb-restricted-cert
  namespace: {{ .Values.keydb.namespace }}
spec:
  secretName: keydb-restricted-tls
  dnsNames:
    - "localhost"
    - "keydb-restricted-keydb-helm"
    - "keydb-restricted-keydb-helm.{{ .Values.keydb.namespace }}"
    - "keydb-restricted-keydb-helm.{{ .Values.keydb.namespace }}.svc"
    - "keydb-restricted-keydb-helm.{{ .Values.keydb.namespace }}.svc.cluster.local"
    - "keydb-restricted-keydb-helm-headless"
    - "keydb-restricted-keydb-helm-headless.{{ .Values.keydb.namespace }}"
    - "keydb-restricted-keydb-helm-headless.{{ .Values.keydb.namespace }}.svc"
    - "*.keydb-restricted-keydb-helm-headless.{{ .Values.keydb.namespace }}.svc"
    - "*.keydb-restricted-keydb-helm-headless.{{ .Values.keydb.namespace }}.svc.cluster.local"
  ipAddresses:
    - "127.0.0.1"
  issuerRef:
    name: {{ .Values.pki.rootCAIssuer }}
    kind: ClusterIssuer
    group: cert-manager.io
  privateKey:
    rotationPolicy: Never
