apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: peerbuckets.blob.loa.kevinpthorne.com
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
spec:
  scope: Namespaced
  group: blob.loa.kevinpthorne.com
  names:
    kind: PeerBucket
    plural: peerbuckets
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    bucketName:
                      type: string
                      description: "The name of the S3 bucket to replicate"
                    sourceCluster:
                      type: string
                      default: "local"  # cluster.local
                    targetCluster:
                      type: string
                  required:
                    - bucketName
                    - targetCluster