apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: servicecertificates.pki.loa.kevinpthorne.com
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true,SkipDryRunOnMissingResource=true  # crossplane installs in this app too; TODO put in other app
    argocd.argoproj.io/sync-wave: "1"
spec:
  scope: Namespaced
  group: pki.loa.kevinpthorne.com
  names:
    kind: ServiceCertificate
    plural: servicecertificates
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    clusterName:
                      type: string
                    sans:
                      type: array
                      description: A list of Subject Alternative Names (SANs).
                      items:
                        type: string
                      default: []
                    ca:
                      type: object
                      description: Certificate Authority details.
                      required:
                        - kind
                        - name
                      properties:
                        kind:
                          type: string
                          description: The CA certificate data or identifier.
                          default: ClusterIssuer
                        name:
                          type: string
                          description: The name of the Certificate Authority.
                          default: app-pki-bootstrap-issuer
                  required:
                    - name