argoNamespace: argo-cd
cluster: {}

pki:
  rootCAIssuer: pki-bootstrap  # currently implied to be ClusterIssuer
  certManagerNamespace: cert-manager

pgedge:
  instances: 1
  appName: "pgedge-cluster"
  namespace: pgedge