argoNamespace: argo-cd
cluster: {}

pki:
  rootCAIssuer: app-pki-bootstrap-issuer  # currently implied to be ClusterIssuer
  certManagerNamespace: cert-manager

pgedge:
  instances: 1
  appName: main
  namespace: pgedge

keydb:
  instances: 1
  namespace: keydb

immich:
  namespace: immich

externaldns:
  namespace: federation-externaldns
  apiKeySecret: cf-key
  apiKeySecretKey: api-key

syncFolders:
  - path: /immich-library

syncBuckets:
  - bucketName: immich-data

cloudflared:
  namespace: federation-cloudflared
  tunnelKeySecret: cf-key
  tunnelKeySecretKey: api-key
  tunnelId: "32cab819-2ee5-4055-8c19-d56a7115b00c"
  domains:
    - "immich.kpt.link"
    - "ident.kpt.link"
    - "mail.k.kpt.link"  # k-apps