argoNamespace: argo-cd
cluster: {}

pki:
  rootCAIssuer: app-pki-bootstrap-issuer  # currently implied to be ClusterIssuer
  certManagerNamespace: cert-manager

pgedge:
  instances: 1
  appName: main
  namespace: pgedge

keydb:
  instances: 0
  namespace: keydb

immich:
  namespace: immich

netbird:
  agent:
    namespace: netbird
  controller:
    namespace: netbird-controller
    subdomain: nb
    dashboardSubdomain: admin.nb

externaldns:
  namespace: federation-externaldns
  apiKeySecret: cf-key
  apiKeySecretKey: api-key