apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: servicecertificate.pki.loa.kevinpthorne.com
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true  # crossplane installs in this app too; TODO put in other app
spec:
  compositeTypeRef:
    apiVersion: pki.loa.kevinpthorne.com/v1alpha1
    kind: ServiceCertificate
  mode: Pipeline
  pipeline:
    - step: patch-and-transform
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - name: service-certificate
            base:
              apiVersion: kubernetes.crossplane.io/v1alpha2
              kind: Object
              spec:
                forProvider:
                  manifest:
                    apiVersion: cert-manager.io/v1
                    kind: Certificate
                    metadata:
                      name: PLACEHOLDER
                      namespace: PLACEHOLDER
                    spec:
                      secretName: PLACEHOLDER
                      dnsNames: []
                        # name
                        # name.namespace.svc
                        # {{ .Values.svcName }}.{{ .Release.Namespace }}.svc.cluster.local
                        # cluster name inside (.svc.cluster.clusterName)
                        # cluster name outside (.clusterName.internal)
                        # sans
                      issuerRef:
                        kind: PLACEHOLDER
                        name: PLACEHOLDER
            patches:
              # name
              - fromFieldPath: metadata.name
                toFieldPath: spec.forProvider.manifest.metadata.name
              # namespace
              - fromFieldPath: metadata.namespace
                toFieldPath: spec.forProvider.manifest.metadata.namespace

              # secret name
              - type: CombineFromComposite
                combine:
                  variables:
                    - fromFieldPath: metadata.name
                  strategy: string
                  string:
                    fmt: "service-cert-%s"
                toFieldPath: spec.forProvider.manifest.spec.secretName
              
              # standard k8s set
              - type: CombineFromComposite
                combine:
                  variables:
                    - fromFieldPath: metadata.name        # Accessible as %[1]s
                    - fromFieldPath: metadata.namespace   # Accessible as %[2]s
                  strategy: string
                  string:
                    fmt: '["%[1]s", "%[1]s.%[2]s.svc", "%[1]s.%[2]s.svc.cluster.local"]'
                transforms:
                  - type: convert
                    convert:
                      toType: list
                      format: json
                toFieldPath: spec.forProvider.manifest.spec.dnsNames
                policy:
                  mergeOptions:
                    appendSlice: true
              # optional cluster federation
              - type: CombineFromComposite
                combine:
                  variables:
                    - fromFieldPath: metadata.name                # Accessible as %[1]s
                    - fromFieldPath: metadata.namespace           # Accessible as %[2]s
                    - fromFieldPath: spec.parameters.clusterName  # Accessible as %[3]s
                  strategy: string
                  string:
                    fmt: '["%[1]s.%[2]s.svc.cluster.%[3]s", "%[1]s.%[3]s.loa.internal"]'
                transforms:
                  - type: convert
                    convert:
                      toType: list
                      format: json
                toFieldPath: spec.forProvider.manifest.spec.dnsNames
                policy:
                  mergeOptions:
                    appendSlice: true
              # optional SANs
              - type: FromCompositeFieldPath
                fromFieldPath: spec.parameters.sans
                toFieldPath: spec.forProvider.manifest.spec.dnsNames
                # If spec.parameters.sans is omitted by the user, Crossplane simply 
                # skips this patch. It will not break or overwrite existing items.
                policy:
                  mergeOptions:
                    appendSlice: true

              # CA Kind
              - fromFieldPath: spec.parameters.ca.kind
                toFieldPath: spec.forProvider.manifest.spec.issuerRef.kind
              # CA Name
              - fromFieldPath: spec.parameters.ca.name
                toFieldPath: spec.forProvider.manifest.spec.issuerRef.name
    - step: automatically-detect-readiness
      functionRef:
        name: function-auto-ready
