apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: secretstore.auth.loa.kevinpthorne.com
spec:
  scoped: Namespaced
  group: auth.loa.kevinpthorne.com
  names:
    kind: SecretStore
    plural: secretstores
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              targetNamespace:
                type: string
                description: "Target namespace of store, or where secrets will originate from"
              replicatorSA:
                type: string
                default: "secret-replicator-sa"
              replicatorNamespace:
                type: string
                default: "external-secrets"
            required:
            - targetNamespace