apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: cluster-secret-store
spec:
  compositeTypeRef:
    apiVersion: secretstore.auth.loa.kevinpthorne.com/v1alpha1
    kind: SecretStore
  resources:
  # Create the Store once
  - name: cluster-store
    base:
      apiVersion: external-secrets.io/v1b1
      kind: ClusterSecretStore
      metadata:
        name: pgedge-cluster-store  # patched to targetNamespace
      spec:
        provider:
          kubernetes:
            remoteNamespace: pgedge
            server:
              url: https://kubernetes.default.svc
              caProvider:
                type: ConfigMap
                name: kube-root-ca.crt
                key: ca.crt
                namespace: kube-system
            auth:
              serviceAccount:
                name: secret-replicator-sa  # patched to replicatorSA
                namespace: external-secrets # patched to replicatorNamespace
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.targetNamespace
      toFieldPath: spec.provider.kubernetes.remoteNamespace
    - type: FromCompositeFieldPath
      fromFieldPath: spec.replicatorSA
      toFieldPath: spec.provider.kubernetes.auth.serviceAccount.name
    - type: FromCompositeFieldPath
      fromFieldPath: spec.replicatorNamespace
      toFieldPath: spec.provider.kubernetes.auth.serviceAccount.namespace
    - type: CombineFromComposite
      combine:
        variables:
        - fromFieldPath: spec.targetNamespace
        strategy: string
        string:
          fmt: "%s-cluster-store"  # must match synced-secret logic
      toFieldPath: metadata.name