apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: cert-replication
  labels:
    provider: kubernetes
    type: cert-replication
spec:
  compositeTypeRef:
    apiVersion: auth.loa.kevinpthorne.com/v1alpha1
    kind: SyncedCert
  mode: Pipeline
  pipeline:
    - step: patch-and-transform
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - name: synced-cert-copy
            base:
              apiVersion: auth.loa.kevinpthorne.com/v1alpha1
              kind: SyncedSecret
              metadata:
                name: PLACEHOLDER
                namespace: PLACEHOLDER
              spec:
                name: PLACEHOLDER
                data:
                  - secretKey: ca.crt
                    remoteRef:
                      key: PLACEHOLDER
                      property: ca.crt
                  - secretKey: tls.crt
                    remoteRef:
                      key: PLACEHOLDER
                      property: tls.crt
                  - secretKey: tls.key
                    remoteRef:
                      key: PLACEHOLDER
                      property: tls.key
                refreshInterval: PLACEHOLDER
                sourceNamespace: PLACEHOLDER
                replicatorSA: PLACEHOLDER
                replicatorNamespace: PLACEHOLDER
            patches:
            - type: CombineFromComposite
              combine:
                variables:
                - fromFieldPath: spec.appName
                - fromFieldPath: spec.certSecretNameSuffix
                strategy: string
                string:
                  fmt: "%s%s-syncedsecretclaim"
              toFieldPath: metadata.name
            - type: CombineFromComposite
              combine:
                variables:
                - fromFieldPath: spec.appName
                - fromFieldPath: spec.certSecretNameSuffix
                strategy: string
                string:
                  fmt: "%s%s"
              toFieldPath: spec.name
              # data
            - type: CombineFromComposite
              combine:
                variables:
                - fromFieldPath: spec.appName
                - fromFieldPath: spec.certSecretNameSuffix
                strategy: string
                string:
                  fmt: "%s%s"
              toFieldPath: "spec.data[0].remoteRef.key" # ca.crt
            - type: CombineFromComposite
              combine:
                variables:
                - fromFieldPath: spec.appName
                - fromFieldPath: spec.certSecretNameSuffix
                strategy: string
                string:
                  fmt: "%s%s"
              toFieldPath: "spec.data[1].remoteRef.key" # tls.crt
            - type: CombineFromComposite
              combine:
                variables:
                - fromFieldPath: spec.appName
                - fromFieldPath: spec.certSecretNameSuffix
                strategy: string
                string:
                  fmt: "%s%s"
              toFieldPath: "spec.data[2].remoteRef.key" # tls.key
              # end data
            - type: FromCompositeFieldPath
              fromFieldPath: spec.refreshInterval
              toFieldPath: spec.refreshInterval
            - type: FromCompositeFieldPath
              fromFieldPath: manifest.namespace
              toFieldPath: manifest.namespace
            - type: FromCompositeFieldPath
              fromFieldPath: spec.sourceNamespace
              toFieldPath: spec.sourceNamespace
            - type: FromCompositeFieldPath
              fromFieldPath: spec.replicatorSA
              toFieldPath: spec.replicatorSA
            - type: FromCompositeFieldPath
              fromFieldPath: spec.replicatorNamespace
              toFieldPath: spec.replicatorNamespace
    - step: automatically-detect-readiness
      functionRef:
        name: function-auto-ready