apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: secret-replication
  labels:
    provider: kubernetes
    type: secret-replication
spec:
  compositeTypeRef:
    apiVersion: auth.loa.kevinpthorne.com/v1alpha1
    kind: SyncedSecret
  mode: Pipeline
  pipeline:
    - step: patch-and-transform
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          # 1. The Role (Allow reading the secret in Source Namespace)
          - name: allow-secret-read-role
            base:
              apiVersion: rbac.authorization.k8s.io/v1
              kind: Role
              metadata:
                name: allow-secret-read # Patched later
                namespace: PLACEHOLDER
              rules:
              - apiGroups: [""]
                resources: ["secrets"]
                verbs: ["get", "list", "watch"]
                resourceNames: ["placeholder"] # Patched later
            patches:
            - type: FromCompositeFieldPath
              fromFieldPath: spec.sourceNamespace
              toFieldPath: spec.forProvider.manifest.metadata.namespace
            - type: FromCompositeFieldPath
              fromFieldPath: spec.name
              toFieldPath: rules[0].resourceNames[0]
            # Generate a unique Role name
            - type: CombineFromComposite
              combine:
                variables:
                - fromFieldPath: spec.name
                strategy: string
                string:
                  fmt: "allow-secret-read-%s"
              toFieldPath: metadata.name
        
          # 2. The RoleBinding (Bind SA to the Role)
          - name: allow-secret-read-binding
            base:
              apiVersion: rbac.authorization.k8s.io/v1
              kind: RoleBinding
              metadata:
                name: allow-secret-read-binding # Patched later
                namespace: PLACEHOLDER
              subjects:
              - kind: ServiceAccount
                name: secret-replicator-sa # Patched later
                namespace: external-secrets # Patched later
              roleRef:
                kind: Role
                name: placeholder-role-name # Patched later
                apiGroup: rbac.authorization.k8s.io
            patches:
            - type: FromCompositeFieldPath
              fromFieldPath: spec.sourceNamespace
              toFieldPath: spec.forProvider.manifest.metadata.namespace
            # Match Role Name
            - type: CombineFromComposite
              combine:
                variables:
                - fromFieldPath: spec.name
                strategy: string
                string:
                  fmt: "allow-secret-read-%s"
              toFieldPath: roleRef.name
            # Generate Binding Name
            - type: CombineFromComposite
              combine:
                variables:
                - fromFieldPath: spec.name
                strategy: string
                string:
                  fmt: "allow-secret-read-%s-binding"
              toFieldPath: metadata.name
            # SA Details
            - type: FromCompositeFieldPath
              fromFieldPath: spec.replicatorSA
              toFieldPath: subjects[0].name
            - type: FromCompositeFieldPath
              fromFieldPath: spec.replicatorNamespace
              toFieldPath: subjects[0].namespace
        
          # 3. The ExternalSecret (The actual copy logic)
          - name: synced-secret-copy
            base:
              apiVersion: external-secrets.io/v1
              kind: ExternalSecret
              metadata:
                annotations:
                  argocd.argoproj.io/sync-wave: "1"
              spec:
                refreshInterval: PLACEHOLDER
                secretStoreRef:
                  name: PLACEHOLDER
                  kind: ClusterSecretStore
                target:
                  name: PLACEHOLDER
                  creationPolicy: Owner
                data: [] # PLACEHOLDER
            patches:
            - type: CombineFromComposite
              combine:
                variables:
                - fromFieldPath: spec.name
                strategy: string
                string:
                  fmt: "%s-copy"
              toFieldPath: metadata.name
            - type: FromCompositeFieldPath
              fromFieldPath: metadata.namespace
              toFieldPath: spec.forProvider.manifest.metadata.namespace
            - type: FromCompositeFieldPath
              fromFieldPath: spec.refreshInterval
              toFieldPath: spec.refreshInterval
            - type: CombineFromComposite
              combine:
                variables:
                - fromFieldPath: spec.sourceNamespace
                strategy: string
                string:
                  fmt: "%s-cluster-store"
              toFieldPath: spec.secretStoreRef.name
            - type: FromCompositeFieldPath
              fromFieldPath: spec.name
              toFieldPath: spec.target.name
            - type: FromCompositeFieldPath
              fromFieldPath: spec.data
              toFieldPath: spec.data
    - step: automatically-detect-readiness
      functionRef:
        name: function-auto-ready