{{- if .Values.edgevpn.generateToken }}
{{- range $key := list "dht" "crypto" "room" "rendezvous" "mdns" }}
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: edgevpn-gen-{{ $key }}
  namespace: {{ $.Release.Namespace }}
spec:
  length: 43
  digits: 5
  symbols: 0
  noUpper: false
  allowRepeat: true
{{- end }}

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.edgevpn.tokenSecretName }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: "0"
  target:
    name: {{ .Values.edgevpn.tokenSecretName }}
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Base64 encode the final YAML structure so it's a valid EdgeVPN token
        {{ .Values.edgevpn.tokenSecretKey }}: '{{ "{{ printf \"otp:\\n  dht:\\n    interval: 360\\n    key: %s\\n    length: 43\\n  crypto:\\n    interval: 360\\n    key: %s\\n    length: 43\\nroom: %s\\nrendezvous: %s\\nmdns: %s\\nmax_message_size: 20971520\\n\" .dht .crypto .room .rendezvous .mdns | b64enc }}" }}'
  data:
    {{- range $key := list "dht" "crypto" "room" "rendezvous" "mdns" }}
    - secretKey: {{ $key }}
      sourceRef:
        generatorRef:
          name: edgevpn-gen-{{ $key }}
          kind: Password
          apiVersion: generators.external-secrets.io/v1alpha1
    {{- end }}
{{- end }}
