image:
  repository: rancher/local-path-provisioner
  tag: v0.0.31
  pullPolicy: IfNotPresent

helperImage:
  repository: busybox
  tag: "1.36.1"

storageClass:
  create: true
  name: local-path
  isDefault: false
  reclaimPolicy: Delete
  volumeBindingMode: WaitForFirstConsumer

nodePathMap:
  - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
    paths:
      - /var/lib/local-path-provisioner

sharedFileSystemPath: ""

rbac:
  create: true

serviceAccount:
  create: true
  name: local-path-provisioner-service-account

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 32Mi

tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule
