apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "keydb.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "keydb.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "keydb.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
