apiVersion: v1
kind: Service
metadata:
  name: {{ include "keydb.fullname" . }}-headless
  labels:
    app.kubernetes.io/name: {{ include "keydb.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  {{- if not (and .Values.tls.enabled .Values.tls.disableNonTls) }}
  - name: server
    port: {{ .Values.port }}
    protocol: TCP
    targetPort: keydb
  {{- end }}
  {{- if .Values.tls.enabled }}
  - name: server-tls
    port: {{ .Values.tls.port }}
    protocol: TCP
    targetPort: keydb-tls
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "keydb.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
