apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: {{ include "adguard.fullname" . }}-password-gen
spec:
  length: 24
  digits: 4
  symbols: 0
  symbolCharacters: ""
  allowRepeat: true
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "adguard.fullname" . }}-auth
spec:
  refreshInterval: "0"
  target:
    name: {{ include "adguard.fullname" . }}-auth
    template:
      engineVersion: v2
      data:
        password: "{{ `{{ .password }}` }}"
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: {{ include "adguard.fullname" . }}-password-gen
