apiVersion: v1
kind: Service
metadata:
  name: {{ include "adguard.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "adguard.name" . }}
    helm.sh/chart: {{ include "adguard.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.webHttpsPort }}
      targetPort: 8443
      protocol: TCP
      name: https
    - port: 8853
      targetPort: 8853
      protocol: TCP
      name: dns-tls
    - port: {{ .Values.service.targetDnsPort }}
      targetPort: 5353
      protocol: UDP
      name: dns-udp
    - port: {{ .Values.service.targetDnsPort }}
      targetPort: 5353
      protocol: TCP
      name: dns-tcp
  selector:
    app.kubernetes.io/name: {{ include "adguard.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
