apiVersion: v1
kind: Service
metadata:
  name: {{ include "adguard.fullname" . }}-lb
  labels:
    app.kubernetes.io/name: {{ include "adguard.name" . }}
    helm.sh/chart: {{ include "adguard.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- if .Values.adguard.staticIP }}
  annotations:
    lbipam.cilium.io/ips: {{ .Values.adguard.staticIP }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 53
      targetPort: {{ .Values.service.targetDnsPort }}
      protocol: UDP
      name: dns-udp
    - port: 53
      targetPort: {{ .Values.service.targetDnsPort }}
      protocol: TCP
      name: dns-tcp
    - port: {{ .Values.service.webHttpsPort }}
      targetPort: 8443
      protocol: TCP
      name: https
    - port: 8853
      targetPort: 8853
      protocol: TCP
      name: dns-tls
  selector:
    app.kubernetes.io/name: {{ include "adguard.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}