argoNamespace: argo-cd
cluster: {}

namespace: hostdns

staticIP: ~
pvc:
  storageClass: longhorn
  size: 100Mi

external-dns:
  provider:
    name: pdns
    
  # Because PowerDNS supports TXT records, 'sync' allows ExternalDNS to automatically 
  # delete records when you delete the corresponding K8s resources.
  policy: sync 

  # Use TXT registry for state tracking
  registry: txt
  # Give your cluster a unique ID so it only manages its own TXT records
  txtOwnerId: unknown

  env:
    - name: EXTERNAL_DNS_PDNS_API_KEY
      valueFrom:
        secretKeyRef:
          name: powerdns-secret
          key: api-key

  extraArgs:
    # The address and port of your PowerDNS webserver/API. 
    # Update this to match your actual PowerDNS server IP or hostname.
    - --pdns-server="http://powerdns.hostdns.svc.cluster.local:8081"
    - --pdns-api-key=$(EXTERNAL_DNS_PDNS_API_KEY)

  domainFilters:
    - .internal

  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534
    fsGroup: 65534

  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop: ["ALL"]
    seccompProfile:
      type: RuntimeDefault

  sources:
    - gateway-tlsroute
    - gateway-tcproute
    - gateway-udproute
    - service

  # filter to non-federation services/gateways
  annotationFilter: "external-dns.loa.internal/expose notin (federation)"