apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netbird-namespace-app
  namespace: {{ .Values.argoNamespace }}
spec:
  project: default
  source:
    repoURL: https://github.com/kevinpthorne/libraryofalexandria.git
    path: pkgs/namespace-helm
    targetRevision: HEAD
    helm:
      releaseName: netbird-namespace
      values: |
        name: {{ .Values.netbird.namespace }}
        podSecurityLevel: 
          enforce: privileged
          audit: privileged
          warn: privileged
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
