apiVersion: db.loa.kevinpthorne.com/v1alpha1
kind: PrivateDatabase
metadata:
  name: keycloak-database
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  databaseName: keycloak
  userName: keycloak
  appNamespace: keycloak
