apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-jgroups-config
  namespace: keycloak
data:
  jgroups-dns-ping.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <infinispan
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="urn:infinispan:config:14.0 http://www.infinispan.org/schemas/infinispan-config-14.0.xsd"
            xmlns="urn:infinispan:config:14.0">
        <jgroups>
            <stack name="dns-ping" extends="tcp">
                <MPING stack.combine="REMOVE" />
                <dns.DNS_PING dns_query="keycloak.keycloak.svc.cluster.{{ .Values.cluster.name }}{{ range .Values.cluster.federateTo }},keycloak.keycloak.svc.cluster.{{ . }}{{ end }}" dns_record_type="A" stack.combine="INSERT_AFTER" stack.position="PING" />
            </stack>
        </jgroups>
    </infinispan>
