apiVersion: v1
kind: Service
metadata:
  name: rtpengine
  namespace: {{ .Release.Name }}-rtpengine
  labels:
    app: rtpengine
spec:
  # THIS IS THE MAGIC LINE. It makes the service "Headless"
  clusterIP: None 
  ports:
    - name: ng-control
      port: 22222
      targetPort: 22222
      protocol: UDP
  selector:
    # This must perfectly match the labels on your RTPEngine DaemonSet pods
    app: rtpengine