apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-gateway
  namespace: {{ .Values.argoNamespace }}
spec:
  project: default
  source:
    repoURL: https://github.com/kevinpthorne/libraryofalexandria.git
    path: pkgs/gateway-helm
    targetRevision: HEAD
    helm:
      valuesObject:
        endpoints:
          - name: grafana
            hostnames:
              - "grafana.{{ .Values.cluster.name }}.loa.internal"
            ports:
              - port: 443
                protocol: TLS
                targetPort: 443
                targetService: prometheus-stack-grafana
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
