apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sipcord.fullname" . | default "sipcord" }}-config
  labels:
    app: sipcord
data:
  config.toml: |
    [sounds]
    
  dialplan.toml: |
    [extensions]
    {{- range .Values.channels }}
    {{ .extension }} = { guild = {{ .guild }}, channel = {{ .channel }} }
    {{- end }}
