apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sipcord.fullname" . | default "sipcord" }}-secret
  labels:
    app: sipcord
type: Opaque
stringData:
  DISCORD_BOT_TOKEN: {{ .Values.discordBotToken | default "" | quote }}
