apiVersion: netbird.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: netbird-provider-config
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true  # crossplane pkg CRD can lag
spec:
  management-uri: {{ include "netbird-api-url" . }}
  credentials-type: token
  credentials:
    source: Secret
    secretRef:
      name: crossplane-netbird-creds
      namespace: crossplane-system
      key: token