apiVersion: vpn.netbird.crossplane.io/v1alpha1
kind: NbGroup
metadata:
  name: cluster-local-group
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true  # crossplane pkg CRD can lag
spec:
  forProvider:
    name: "cluster-local-nodes"
  providerConfigRef:
    name: netbird-provider-config
{{- range .Values.cluster.federateTo }}
---
apiVersion: vpn.netbird.crossplane.io/v1alpha1
kind: NbGroup
metadata:
  name: "cluster-{{ . }}-group"
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true  # crossplane pkg CRD can lag
spec:
  forProvider:
    name: "cluster-{{ . }}-nodes"
  providerConfigRef:
    name: netbird-provider-config
{{- end }}
