apiVersion: netbird.io/v1alpha1
kind: SetupKey
metadata:
  name: cluster-local-setup-key
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true  # crossplane pkg CRD can lag
spec:
  forProvider:
    name: "k8s-cluster-local-nodes"
    type: "reusable"
    ephemeral: true
    # 0 = unlimited usage (required for K8s autoscaling)
    usageLimit: 0 
    # Link to the Crossplane Group resource above
    autoGroupsRefs:
      - name: cluster-local-group
  
  # THE GITOPS MAGIC:
  # Crossplane will extract the created Setup Key from the NetBird API 
  # and write it into this local Kubernetes Secret.
  writeConnectionSecretToRef:
    name: netbird-setup-key
    namespace: netbird