apiVersion: vpn.netbird.crossplane.io/v1alpha1
kind: NbSetupKey
metadata:
  name: cluster-local-setup-key
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true  # crossplane pkg CRD can lag
spec:
  forProvider:
    name: "k8s-cluster-local-nodes"
    allow_extra_dns_labels: true
    revoked: false
    type: "reusable"
    ephemeral: true
    expires_in: 86400
    usage_limit: 0
    auto_groups:
      - cluster-local-group
  providerConfigRef:
    name: netbird-provider-config
  writeConnectionSecretToRef:
    name: netbird-setup-key
    namespace: netbird