apiVersion: seaweed.seaweedfs.com/v1
kind: Seaweed
metadata:
  name: seaweed-cluster
  namespace: seaweedfs-system
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  tls:
    enabled: true
    issuerRef:
      name: app-pki-bootstrap-issuer
      kind: ClusterIssuer
  image: chrislusf/seaweedfs:4.01
  volume:
    replicas: 1
    storageClassName: {{ .Values.seaweedfs.storageClass | quote }}
    requests:
      storage: {{ .Values.seaweedfs.size | quote }}
    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      seccompProfile:
        type: RuntimeDefault
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      runAsNonRoot: true
      runAsUser: 1000
  filer:
    replicas: 1
    persistence:
      enabled: true
      storageClassName: {{ .Values.seaweedfs.storageClass | quote }}
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: "10Gi"
    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      seccompProfile:
        type: RuntimeDefault
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      runAsNonRoot: true
      runAsUser: 1000
  master:
    replicas: 1
    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      seccompProfile:
        type: RuntimeDefault
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      runAsNonRoot: true
      runAsUser: 1000
  s3:
    enabled: true
    replicas: 1
    extraArgs:
      - "-cert.file=/etc/sw-tls/tls.crt"
      - "-key.file=/etc/sw-tls/tls.key"
    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
      seccompProfile:
        type: RuntimeDefault
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      runAsNonRoot: true
      runAsUser: 1000