apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homeassistant-tls
  namespace: {{ .Values.argoNamespace }}
spec:
  project: default
  source:
    repoURL: https://github.com/kevinpthorne/libraryofalexandria.git
    path: pkgs/service-tls-helm
    targetRevision: HEAD
    helm:
      valuesObject:
        svcName: "homeassistant"
        cert:
          sans:
            - "homeassistant.k.loa.internal"
  destination:
    server: https://kubernetes.default.svc
    namespace: homeassistant
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
