apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minecraft
  namespace: {{ .Values.argoNamespace }}
spec:
  project: default
  source:
    repoURL: https://github.com/kevinpthorne/libraryofalexandria.git
    path: apps/minecraft-server
    targetRevision: HEAD
    helm:
      valuesObject:
        service:
          domains:
            - mc.k.loa.internal
            - mc.k.kpt.link
          public: true
  destination:
    server: https://kubernetes.default.svc
    namespace: minecraft
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    # pull from internet
    managedNamespaceMetadata:
      labels:
        zarf.dev/agent: "ignore"