apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unifi
  namespace: {{ .Values.argoNamespace }}
spec:
  project: default
  source:
    repoURL: https://github.com/kevinpthorne/libraryofalexandria.git
    path: apps/unifi
    targetRevision: HEAD
    helm:
      valuesObject:
        service:
          domains:
            - unifi.k.loa.internal
  destination:
    server: https://kubernetes.default.svc
    namespace: unifi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        zarf.dev/agent: "ignore"