{{- $cluster := .Values.cluster | default dict -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden
  namespace: {{ .Values.argoNamespace }}
spec:
  project: default
  source:
    repoURL: https://charts.pascaliske.dev
    chart: vaultwarden
    targetRevision: 2.0.0
    helm:
      valuesObject:
        controller:
          kind: StatefulSet
          replicas: 1
        podSecurityContext:
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000
          seccompProfile:
            type: RuntimeDefault
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        env:
          - name: DOMAIN
            value: "https://vaultwarden.{{ $cluster.name | default "k" }}.loa.internal"
          - name: TZ
            value: "EDT"
          - name: ROCKET_TLS
            value: '{certs="/certs/tls.crt",key="/certs/tls.key"}'
        extraVolumes:
          - name: tls
            secret:
              secretName: vaultwarden-tls
        extraVolumeMounts:
          - name: tls
            mountPath: /certs
            readOnly: true
        persistentVolumeClaim:
          create: true
          accessMode: ReadWriteOnce
          size: 5Gi
          storageClassName: "longhorn"
  destination:
    server: https://kubernetes.default.svc
    namespace: vaultwarden
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        zarf.dev/agent: "ignore"

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden-tls
  namespace: {{ .Values.argoNamespace }}
spec:
  project: default
  source:
    repoURL: https://github.com/kevinpthorne/libraryofalexandria.git
    path: pkgs/service-tls-helm
    targetRevision: HEAD
    helm:
      valuesObject:
        svcName: "vaultwarden"
        cluster:
          name: {{ $cluster.name | default "k" }}
        cert:
          secretName: "vaultwarden-tls"
          sans:
            - "vaultwarden.{{ $cluster.name | default "k" }}.loa.internal"
  destination:
    server: https://kubernetes.default.svc
    namespace: vaultwarden
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden-gateway
  namespace: {{ .Values.argoNamespace }}
spec:
  project: default
  source:
    repoURL: https://github.com/kevinpthorne/libraryofalexandria.git
    path: pkgs/gateway-helm
    targetRevision: HEAD
    helm:
      valuesObject:
        endpoints:
          - name: vaultwarden
            createGateway: false
            gatewayName: local-gateway
            gatewayNamespace: kube-system
            hostnames:
              - "vaultwarden.{{ $cluster.name | default "k" }}.loa.internal"
            ports:
              - port: 443
                protocol: TLS
                targetPort: 80
                targetService: vaultwarden
                tls:
                  mode: Passthrough
  destination:
    server: https://kubernetes.default.svc
    namespace: vaultwarden
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
