apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webmail
  namespace: {{ .Values.argoNamespace }}
spec:
  project: default
  source:
    repoURL: https://l4gdev.github.io/helm-charts
    targetRevision: ">=0.2.0"
    chart: bulwark-mail
    helm:
      valuesObject:
        config:
          jmapServerUrl: "https://mail.k.kpt.link"
        settingsSync:
          enabled: true
          persistence:
            enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: mail
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webmail-gateway
  namespace: {{ .Values.argoNamespace }}
spec:
  project: default
  source:
    repoURL: https://github.com/kevinpthorne/libraryofalexandria.git
    path: pkgs/gateway-helm
    targetRevision: HEAD
    helm:
      valuesObject:
        endpoints:
          - name: webmail
            createGateway: false
            gatewayName: local-gateway
            gatewayNamespace: kube-system
            hostnames:
              - "webmail.k.loa.internal"
              - "webmail.k.kpt.link"
            ports:
              - port: 443
                protocol: HTTP
                targetPort: 80
                targetService: webmail-bulwark-mail
  destination:
    server: https://kubernetes.default.svc
    namespace: mail
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
