apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: powerdns-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.pvc.storageClass }}
  resources:
    requests:
      storage: {{ .Values.pvc.size }}