apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: powerdns-gateway-app
  namespace: {{ .Values.argoNamespace }}
spec:
  project: default
  source:
    repoURL: https://github.com/kevinpthorne/libraryofalexandria.git
    path: pkgs/gateway-helm
    targetRevision: HEAD
    helm:
      values: |
        endpoints:
        - name: powerdns-app
          {{- if .Values.staticIP }}
          addresses:
            - IPAddress: {{ .Values.staticIP }}
          {{- end }}
          ports:
            - port: 53
              targetPort: 5353
              protocol: UDP
              targetService: powerdns
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Release.Namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    # pull from internet
    managedNamespaceMetadata:
      labels:
        zarf.dev/agent: "ignore"