apiVersion: apps/v1
kind: Deployment
metadata:
  name: powerdns
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: powerdns
  template:
    metadata:
      labels:
        app: powerdns
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10000
        runAsGroup: 10000
        fsGroup: 10000
      initContainers:
      - name: init-sqlite
        image: alpine:latest
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["ALL"]
          seccompProfile:
            type: RuntimeDefault
        command: ["/bin/sh", "-c"]
        args:
        - |
          if [ ! -s /var/lib/powerdns/pdns.sqlite3 ]; then
            cd /var/lib/powerdns
            wget -qO sqlite.zip https://www.sqlite.org/2024/sqlite-tools-linux-x64-3450300.zip
            unzip -q sqlite.zip
            wget -qO schema.sql https://raw.githubusercontent.com/PowerDNS/pdns/rel/auth-5.0.x/modules/gsqlite3backend/schema.sqlite3.sql
            ./sqlite-tools-linux-x64-3450300/sqlite3 pdns.sqlite3 < schema.sql
            rm -rf sqlite.zip sqlite-tools-linux-x64-3450300 schema.sql
          fi
        volumeMounts:
        - name: pdns-storage
          mountPath: /var/lib/powerdns
      containers:
      - name: powerdns
        image: powerdns/pdns-auth-50:5.0.4
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["ALL"]
          seccompProfile:
            type: RuntimeDefault
        env:
        - name: PDNS_API_KEY
          valueFrom:
            secretKeyRef:
              name: powerdns-secret
              key: api-key
        - name: SSL_CERT_FILE
          value: /etc/ssl/certs/ca-bundle.crt
        ports:
        - containerPort: 5353
          protocol: UDP
        - containerPort: 5353
          protocol: TCP
        - containerPort: 8081 # The API port for ExternalDNS
          protocol: TCP

        args:
        - "--api=yes"
        - "--api-key=$(PDNS_API_KEY)" # ExternalDNS uses this
        - "--webserver=yes"
        - "--webserver-address=0.0.0.0"
        - "--webserver-port=8081"
        - "--launch=gsqlite3"
        - "--gsqlite3-database=/var/lib/powerdns/pdns.sqlite3"
        - "--gsqlite3-dnssec=yes"
        volumeMounts:
        - name: pdns-storage
          mountPath: /var/lib/powerdns
        - name: trusted-ca-volume
          mountPath: /etc/ssl/certs/custom-trusted-ca.pem
          subPath: ca-bundle.crt
        - name: pdns-run
          mountPath: /var/run
      volumes:
      - name: pdns-storage
        persistentVolumeClaim:
          claimName: powerdns-pvc # Maps to a simple 1GB PVC
      - name: trusted-ca-volume
        configMap:
          name: trusted-ca-bundle
      - name: pdns-run
        emptyDir: {}