{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: mc-java-route
  labels:
    {{- include "minecraft-server.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: minecraft-gateway
      sectionName: tcp-25565
  rules:
    - backendRefs:
      - name: minecraft-minecraft-server
        port: {{ .Values.service.javaPort }}
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: UDPRoute
metadata:
  name: mc-bedrock-route
  labels:
    {{- include "minecraft-server.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: minecraft-gateway
      sectionName: udp-19132
  rules:
    - backendRefs:
      - name: minecraft-minecraft-server
        port: {{ .Values.service.bedrockPort }}
{{- end }}