apiVersion: v1
kind: Service
metadata:
  name: {{ include "minecraft-server.fullname" . }}
  labels:
    {{- include "minecraft-server.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.service.domains }}
    external-dns.alpha.kubernetes.io/hostname: '{{ join "," .Values.service.domains | quote }}'
    {{- if .Values.service.public }}
    external-dns.loa.internal/expose: "public"
    {{- end }}
    {{- else }}
    {}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.javaPort }}
      targetPort: mc-java
      protocol: TCP
      name: mc-java
    - port: {{ .Values.service.bedrockPort }}
      targetPort: mc-bedrock
      protocol: UDP
      name: mc-bedrock
  selector:
    {{- include "minecraft-server.selectorLabels" . | nindent 4 }}
