apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pihole.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "pihole.name" . }}
    helm.sh/chart: {{ include "pihole.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  02-custom.conf: |
    # Listen on 5353 instead of 53
    port={{ .Values.service.targetDnsPort }}
  05-forwarders.conf: |
    {{- range .Values.pihole.dnsServers }}
    server={{ . }}
    {{- end }}
  custom.list: |
    {{- range .Values.pihole.customDns }}
    {{ . }}
    {{- end }}
  external.conf: |
    server.modules += ( "mod_openssl" )
    $SERVER["socket"] == ":8443" {
      ssl.engine  = "enable"
      ssl.pemfile = "/etc/pihole-tls/tls.crt"
      ssl.privkey = "/etc/pihole-tls/tls.key"
    }
