# 1. Define the Password Generator
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: pihole-password-gen
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "pihole.name" . }}
    helm.sh/chart: {{ include "pihole.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  length: 24
  digits: 5
  symbols: 0
  noUpper: false
  allowRepeat: true

---
# 2. Define the ExternalSecret to create the K8s Secret
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "pihole.fullname" . }}-auth
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "pihole.name" . }}
    helm.sh/chart: {{ include "pihole.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  refreshInterval: "0" 
  target:
    name: {{ include "pihole.fullname" . }}-auth
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        password: '{{ "{{ .password }}" }}'
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: pihole-password-gen
