apiVersion: v1
kind: Service
metadata:
  name: {{ include "pihole.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "pihole.name" . }}
    helm.sh/chart: {{ include "pihole.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- if .Values.service.domain }}
    annotations:
      external-dns.alpha.kubernetes.io/hostname: {{ .Values.service.domain }}
    {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.webPort }}
      targetPort: 8443
      protocol: TCP
      name: https
  selector:
    app.kubernetes.io/name: {{ include "pihole.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pihole.fullname" . }}-dns
  labels:
    app.kubernetes.io/name: {{ include "pihole.name" . }}
    helm.sh/chart: {{ include "pihole.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- if .Values.service.staticIP }}
  annotations:
    lbipam.cilium.io/ips: {{ .Values.service.staticIP }}
  {{- end }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.service.dnsPort }}
      targetPort: {{ .Values.service.targetDnsPort }}
      protocol: UDP
      name: dns-udp
    - port: {{ .Values.service.dnsPort }}
      targetPort: {{ .Values.service.targetDnsPort }}
      protocol: TCP
      name: dns-tcp
  selector:
    app.kubernetes.io/name: {{ include "pihole.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
