apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.name }}
  labels:
    pod-security.kubernetes.io/enforce: {{ .Values.podSecurityLevel.enforce }}
    pod-security.kubernetes.io/audit: {{ .Values.podSecurityLevel.audit }}
    pod-security.kubernetes.io/warn: {{ .Values.podSecurityLevel.warn }}