apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-ddns
  labels:
    app: cloudflare-ddns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflare-ddns
  template:
    metadata:
      labels:
        app: cloudflare-ddns
    spec:
      containers:
        - name: cloudflare-ddns
          image: timothyjmiller/cloudflare-ddns:2.1.2
          imagePullPolicy: IfNotPresent
          env:
            - name: CLOUDFLARE_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.global.apiKeySecret }}"
                  key: "{{ .Values.global.apiKeySecretKey }}"
            - name: DOMAINS
              value: "{{ .Values.global.ddnsDomain }}"
            - name: PROXIED
              value: "false"
            - name: IP4_PROVIDER
              value: "cloudflare.trace"
            - name: IP6_PROVIDER
              value: "none"
