apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kro
  namespace: {{ .Values.argoNamespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    chart: kro
    repoURL: oci://registry.k8s.io/kro/charts/kro
    targetRevision: 0.9.2
  destination:
    server: https://kubernetes.default.svc
    namespace: kro-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        zarf.dev/agent: "ignore"
