apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kro
  namespace: {{ .Values.argoNamespace }}
spec:
  project: default
  source:
    chart: kro
    repoURL: oci://ghcr.io/kro-run/kro/kro
    targetRevision: 0.1.0
  destination:
    server: https://kubernetes.default.svc
    namespace: kro-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        zarf.dev/agent: "ignore"
