apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seaweedfs-operator
  namespace: {{ .Values.argoNamespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    chart: seaweedfs-operator
    repoURL: https://seaweedfs.github.io/seaweedfs-operator/
    targetRevision: 0.1.28
    helm:
      values: |
        podSecurityContext:
          runAsNonRoot: true
          runAsUser: 65532
          fsGroup: 65532
          seccompProfile:
            type: RuntimeDefault
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
  destination:
    server: https://kubernetes.default.svc
    namespace: seaweedfs-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        zarf.dev/agent: "ignore"
        pod-security.kubernetes.io/enforce: privileged
