apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seaweedfs
  namespace: {{ .Values.argoNamespace }}
spec:
  project: default
  
  source:
    repoURL: https://seaweedfs.github.io/seaweedfs/helm
    chart: seaweedfs
    targetRevision: '4.0.401' # Pin to a specific chart version
    helm:
      values: |
        global:
          enableSecurity: true
        master:
          replicas: 1  # set to master count
          data:
            type: persistentVolumeClaim
            size: 1G
            storageClass: longhorn
          containerSecurityContext:
            capabilities:
              drop:
                - ALL
          podSecurityContext:
            runAsNonRoot: true
            seccompPorfile:
              type: RuntimeDefault
        volume:
          replicas: 1
          dataDirs:
            - name: data1
              type: persistentVolumeClaim
              size: 250G
              storageClass: longhorn
          containerSecurityContext:
            capabilities:
              drop:
                - ALL
          podSecurityContext:
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
        filer:
          containerSecurityContext:
            capabilities:
              drop:
                - ALL
          podSecurityContext:
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          s3:
            enabled: true
        sftp:
          enabled: true
          containerSecurityContext:
            enabled: true
            capabilities:
              drop:
                - ALL
          podSecurityContext:
            enabled: true
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
        csi:
          enabled: false
        
  destination:
    server: https://kubernetes.default.svc
    namespace: seaweedfs-system
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true