apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterSPIFFEID
metadata:
  name: "seaweedfs-spiffeid"
spec:
  # 1. The Naming Convention
  # This creates a predictable ID for every service in your cluster.
  # Example result: spiffe://cluster1.internal/ns/default/sa/backend-api
  spiffeIDTemplate: "{{ .Values.seaweedfs.spiffeIDTemplate }}"

  # 2. Select the pods (Ensure these match your pod labels)
  podSelector:
    matchLabels:
      app.kubernetes.io/name: seaweedfs
      app.kubernetes.io/instance: seaweedfs

  # 3. IMPORTANT: Define DNS names (SANs)
  #    Vault needs these to verify the cert matches the service address.
  dnsNameTemplates:
    - "seaweedfs"
    - "seaweedfs.seaweedfs-system.svc.cluster.local"
    - "seaweedfs-active.seaweedfs-system.svc.cluster.local"
    - "seaweedfs-standby.seaweedfs-system.svc.cluster.local"
    # - "localhost"
