apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: syncfolders
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  schema:
    apiVersion: v1alpha1
    kind: SyncFolder
    group: fs.loa.kevinpthorne.com
    spec:
      path: string
      sourceCluster: "string | default=local"
      targetCluster: string
  resources:
    - id: filerSyncDeployment
      template:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: "seaweedfs-sync-${schema.metadata.name}"
          namespace: seaweedfs-system
          labels: >-
            ${has(schema.metadata.labels) && "argocd.argoproj.io/instance" in schema.metadata.labels ? {"argocd.argoproj.io/instance": schema.metadata.labels["argocd.argoproj.io/instance"]} : {}}
          annotations: >-
            ${has(schema.metadata.annotations) && "argocd.argoproj.io/tracking-id" in schema.metadata.annotations ? {"argocd.argoproj.io/tracking-id": schema.metadata.annotations["argocd.argoproj.io/tracking-id"]} : {}}
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: seaweedfs-filer-sync
          template:
            metadata:
              labels:
                app: seaweedfs-filer-sync
            spec:
              securityContext:
                runAsNonRoot: true
                runAsUser: 1000
                runAsGroup: 1000
                fsGroup: 1000
                seccompProfile:
                  type: RuntimeDefault
              containers:
              - name: filer-sync
                image: chrislusf/seaweedfs:4.33
                command:
                  - "weed"
                  - "-logtostderr=true"
                  - "-config_dir=/etc/sw-security"
                  - "filer.sync"
                args:
                  - "-a=seaweed-cluster-filer.seaweedfs-system.svc.cluster.${schema.spec.sourceCluster}:8888"
                  - "-b=seaweed-cluster-filer.seaweedfs-system.svc.cluster.${schema.spec.targetCluster}:8888"
                  - "-a.path=${schema.spec.path}"
                  - "-b.path=${schema.spec.path}"
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                      - ALL
                  runAsNonRoot: true
                  runAsUser: 1000
                env:
                  - name: SSL_CERT_FILE
                    value: "/certs/cas/ca-bundle.crt"
                volumeMounts:
                  - name: sw-security
                    mountPath: /etc/sw-security
                    readOnly: true
                  - name: sw-tls
                    mountPath: /etc/sw-tls
                    readOnly: true
                  - name: trusted-ca
                    mountPath: /certs/cas
                    readOnly: true
              volumes:
                - name: sw-security
                  configMap:
                    name: seaweed-cluster-security-config
                - name: sw-tls
                  secret:
                    secretName: seaweed-cluster-server-tls
                - name: trusted-ca
                  configMap:
                    name: trusted-ca-bundle
