apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: k8s-local-crossplane
spec:
  provider:
    kubernetes:
      server:
        url: "https://kubernetes.default.svc.cluster.local"
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
          namespace: crossplane-system
      auth:
        serviceAccount:
          # This matches the SA we bound the Role to
          name: crossplane
          namespace: crossplane-system