replicaCount: 1

image:
  repository: pihole/pihole
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  staticIP: ~
  domain: ~
  dnsPort: 53
  targetDnsPort: 5353
  webPort: 443

pihole:
  tz: "UTC"
  # DNS servers to forward queries to
  dnsServers:
    - 1.1.1.1
    - 8.8.8.8
  # Custom DNS records to populate custom.list
  customDns: []
    # - "192.168.1.10 example.com"
