apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-bootstrap-config
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  configuration.yaml: |
    # Loads default set of integrations. Do not remove.
    default_config:

    # Load frontend themes from the themes folder
    frontend:
      themes: !include_dir_merge_named themes

    automation: !include automations.yaml
    script: !include scripts.yaml
    scene: !include scenes.yaml

    # Enable TLS for Home Assistant Gateway
    http:
      ssl_certificate: /ssl/tls.crt
      ssl_key: /ssl/tls.key
