apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-asterisk
spec:
  serviceName: {{ .Release.Name }}-asterisk
  replicas: {{ .Values.asterisk.replicaCount }}
  selector:
    matchLabels:
      app: asterisk
  template:
    metadata:
      labels:
        app: asterisk
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/asterisk/configmap.yaml") . | sha256sum }}
    spec:
      initContainers:
        - name: init-asterisk-lib
          image: {{ .Values.asterisk.image }}
          command: ['sh', '-c', 'cp -R /var/lib/asterisk/* /mnt/asterisk-lib/ 2>/dev/null || true']
          volumeMounts:
            - name: asterisk-lib
              mountPath: /mnt/asterisk-lib
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
      containers:
        - name: asterisk
          image: {{ .Values.asterisk.image }}
          command: ["/usr/sbin/asterisk", "-f", "-vvvddd"]
          ports:
            - name: sip-internal
              containerPort: {{ .Values.asterisk.ports.sip }}
              protocol: UDP
          volumeMounts:
            - name: asterisk-config-volume
              mountPath: /etc/asterisk/pjsip.conf
              subPath: pjsip.conf
            - name: asterisk-config-volume
              mountPath: /etc/asterisk/extensions.conf
              subPath: extensions.conf
            - name: asterisk-run
              mountPath: /var/run/asterisk
            - name: asterisk-spool
              mountPath: /var/spool/asterisk
            - name: asterisk-log
              mountPath: /var/log/asterisk
            - name: asterisk-lib
              mountPath: /var/lib/asterisk
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
      securityContext:
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: asterisk-config-volume
          configMap:
            name: asterisk-config
        - name: asterisk-run
          emptyDir: {}
        - name: asterisk-spool
          emptyDir: {}
        - name: asterisk-log
          emptyDir: {}
        - name: asterisk-lib
          emptyDir: {}