apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-asterisk
spec:
  type: ClusterIP # Strictly internal
  ports:
    - name: sip
      port: {{ .Values.asterisk.ports.sip }}
      targetPort: sip-internal
      protocol: UDP
    - name: sip-tls
      port: {{ .Values.asterisk.ports.tls }}
      targetPort: sip-tls
      protocol: TCP
  selector:
    app: asterisk