---
# templates/cilium-ipsec-secret.yaml
{{- $secretName := .Values.name }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace $secretName) }}
{{- $keyID := 3 }}
{{- $algo := "rfc4106(gcm(aes))" }}
{{- $keySize := 128 }}

# 🔑 Logic to check for existing key, otherwise generate a new one
{{- $pskHex := "" }}
{{- if $secret }}
  {{- $existingKeys := index $secret.data "keys" | b64dec }}
  # Extract the existing PSK (the third element in the key string)
  {{- $pskHex = index (splitList " " $existingKeys) 2 }}
{{- else }}
  # Generate a new 40-character (20-byte) random alphanumeric string
  # Then convert the alphanumeric string to a sequence of hex characters (0-9, a-f)
  {{- $randBytes := (randAlphaNum 32) }}
  {{- $pskHex = $randBytes | sha256sum | nospace | trunc 40 }}
{{- end }}

# Final key string format: key-id encryption-algorithm PSK-in-hex-format key-size
{{- $keyString := printf "%s+ %s %s %s" (toString $keyID) $algo $pskHex (toString $keySize) }}

# --- The Kubernetes Secret Resource ---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  # The final, combined key string (Base64 encoding is handled by stringData)
  keys: {{ $keyString | quote }}