argoNamespace: argo-cd
cluster: {}

seaweedfs:
  storageClass: longhorn
  size: 600G
  spiffeIDTemplate: "spiffe://{{ .TrustDomain }}/ns/{{ .PodMeta.Namespace }}/sa/{{ .PodMeta.ServiceAccountName }}"

hostdns:
  enabled: true

cloudflareExternaldns:
  enabled: true