argoNamespace: argo-cd
cluster: {}

seaweedfs:
  storageClass: longhorn
  size: 250G
  spiffeIDTemplate: "spiffe://{{ .TrustDomain }}/ns/{{ .PodMeta.Namespace }}/sa/{{ .PodMeta.ServiceAccountName }}"

hostdns:
  enabled: true

externaldns:
  enabled: true
  apiKeySecret: cf-key
  apiKeySecretKey: api-key