replicaCount: 1

image:
  repository: ghcr.io/home-assistant/home-assistant
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

timezone: "EST"

service:
  type: LoadBalancer
  port: 8123

persistence:
  enabled: true
  storageClass: "longhorn"
  accessMode: ReadWriteOnce
  size: 10Gi
  mountPath: /config

resources:
  limits:
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 512Mi
