{
  pkgs,
  lib,
  stdenv,
  fetchFromGitHub,
  fetchurl,
  autoconf,
  automake,
  libtool,
  pkg-config,
  alsa-lib,
  libpulseaudio,
  gtk2,
  ffmpeg,
  coreutils,
  gnugrep,
  gnused,
  gawk,
}:

stdenv.mkDerivation rec {
  pname = "dectalk-asterisk";
  version = "master";

  src = fetchFromGitHub {
    owner = "dectalk";
    repo = "dectalk";
    rev = "69ebb459137a7a8d92ed41da8362233eaa173efc";
    sha256 = "0r1c9z3zb9ah3xr25zvgja4mp7qxw35bvhwvn3020z926960ljqy";
  };

  coreSounds = fetchurl {
    url = "https://downloads.asterisk.org/pub/telephony/sounds/asterisk-core-sounds-en-wav-current.tar.gz";
    sha256 = "02zc671rjcj4ypk5sagwbs2j2iffxhawsvd9scss4zjnchvm9b87";
  };

  nativeBuildInputs = [
    autoconf
    automake
    libtool
    pkg-config
    ffmpeg
    coreutils
    gnugrep
    gnused
    gawk
  ];

  buildInputs = [
    gtk2
  ];

  configureFlags = [
    "--disable-audio"
  ];

  preConfigure = ''
    cd src
    # Patch configure.ac so it doesn't run git commands, since fetchFromGitHub removes .git
    sed -i 's/m4_esyscmd_s(echo $(git describe.*)/[master],/' configure.ac
    # Autoconf needs AC_CONFIG_SRCDIR to verify the source directory
    sed -i '/AC_CANONICAL_TARGET/a AC_CONFIG_SRCDIR([DECtalk.c])' configure.ac
    ./autogen.sh
  '';

  installPhase = ''
    mkdir -p $out/bin
    mkdir -p $out/share/dectalk
    mkdir -p $out/share/asterisk/sounds/dectalk
    
    # The build produces files in the ../dist folder
    cp -r ../dist/* $out/share/dectalk/
    
    # Remove broken symlinks generated by DECtalk in usr/bin
    rm -rf $out/share/dectalk/usr
    
    # Symlink the binary so it's in PATH
    if [ -f $out/share/dectalk/say ]; then
      ln -s $out/share/dectalk/say $out/bin/dectalk-say
    else
      echo "Cannot find 'say' binary in dist!"
      exit 1
    fi

    # Create the wrapper script for AGI streaming
    cp ${./dectalk_stream.sh} $out/bin/dectalk_stream.sh
    sed -i "s|@out@|$out|g" $out/bin/dectalk_stream.sh
    chmod +x $out/bin/dectalk_stream.sh

    # --- STATIC SOUND GENERATOR ---
    cp ${./generate_sounds.sh} /tmp/generate_sounds.sh
    sed -i "s|@out@|$out|g" /tmp/generate_sounds.sh
    chmod +x /tmp/generate_sounds.sh
    export CORE_SOUNDS=${coreSounds}
    bash /tmp/generate_sounds.sh
  '';
}
