apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: admin-client-cert
  namespace: crossplane-system  # TODO: this should be fed in via values.yaml
spec:
  secretName: admin-client-cert
  usages:
    - client auth
  commonName: admin
  issuerRef:
    name: pgedge-{{ .Values.pgedge.appName }}-client-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  privateKey:
    rotationPolicy: Never