apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pgedge-{{ .Values.pgedge.appName }}-client-ca
  namespace: {{ .Values.pki.certManagerNamespace }}
spec:
  isCA: true
  commonName: "{{ .Values.pki.rootCAIssuer }}-pgedge-{{ .Values.pgedge.appName }}-client-ca"
  secretName: pgedge-{{ .Values.pgedge.appName }}-client-ca-key-pair
  secretTemplate:
    labels:
      pki.loa.kevinpthorne.com/trusted-ca: "true"
  privateKey:
    algorithm: RSA
    size: 2048
    rotationPolicy: Never
  issuerRef:
    name: {{ .Values.pki.rootCAIssuer }}
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: pgedge-{{ .Values.pgedge.appName }}-client-ca-issuer
spec:
  ca:
    secretName: pgedge-{{ .Values.pgedge.appName }}-client-ca-key-pair