apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pgedge-{{ .Values.pgedge.appName }}-client-ca
  namespace: {{ .Values.pki.certManagerNamespace }}
spec:
  isCA: true
  commonName: "{{ .Values.pki.rootCAIssuer }}-pgedge-{{ .Values.pgedge.appName }}-client-ca"
  secretName: pgedge-{{ .Values.pgedge.appName }}-client-ca-key-pair
  secretTemplate:
    labels:
      pki.loa.kevinpthorne.com/trusted-ca: "true"
  privateKey:
    algorithm: RSA
    size: 2048
    rotationPolicy: Never
  issuerRef:
    name: {{ .Values.pki.rootCAIssuer }}
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: pgedge-{{ .Values.pgedge.appName }}-client-ca-issuer
spec:
  ca:
    secretName: pgedge-{{ .Values.pgedge.appName }}-client-ca-key-pair
---
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  # This dictates the name of the Secret that will be created in the target namespace
  name: pgedge-{{ .Values.pgedge.appName }}-client-ca-public
spec:
  sources:
    - secret:
        # The name of the master CA secret attached to your ClusterIssuer
        name: pgedge-{{ .Values.pgedge.appName }}-client-ca-key-pair
        # cert-manager usually stores the public certificate under 'tls.crt'
        key: tls.crt
  target:
    # Tell trust-manager to output a Secret, not a ConfigMap
    secret:
      # CloudNativePG expects the key inside the secret to be named exactly 'ca.crt'
      key: ca.crt
    namespaceSelector:
      matchLabels:
        # This standard Kubernetes label ensures it only syncs to the pgedge namespace
        kubernetes.io/metadata.name: {{ .Values.pgedge.namespace }}