apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "unifi.fullname" . }}-mongodb-init
  labels:
    {{- include "unifi.labels" . | nindent 4 }}
data:
  init-mongo.sh: |
    #!/bin/bash
    if which mongosh > /dev/null 2>&1; then mongo_init_bin='mongosh --tls --tlsAllowInvalidCertificates'; else mongo_init_bin='mongo --ssl --sslAllowInvalidCertificates'; fi
    ${mongo_init_bin} <<EOF
    use admin
    db.createUser({
      user: "${MONGO_USER}",
      pwd: "${MONGO_PASS}",
      roles: [
        { db: "${MONGO_DBNAME}", role: "dbOwner" },
        { db: "${MONGO_DBNAME}_stat", role: "dbOwner" },
        { db: "${MONGO_DBNAME}_audit", role: "dbOwner" }
      ]
    })
    EOF
