apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: {{ include "unifi.fullname" . }}-db-credentials-gen
  labels:
    {{- include "unifi.labels" . | nindent 4 }}
spec:
  length: 24
  digits: 4
  symbols: 0
  allowRepeat: true
  secretKeys:
    - root_password
    - unifi_password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "unifi.fullname" . }}-db-credentials
  labels:
    {{- include "unifi.labels" . | nindent 4 }}
spec:
  refreshInterval: "0"
  target:
    name: {{ include "unifi.fullname" . }}-db-credentials
    template:
      engineVersion: v2
      data:
        root-password: "{{ `{{ .root_password }}` }}"
        unifi-password: "{{ `{{ .unifi_password }}` }}"
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: {{ include "unifi.fullname" . }}-db-credentials-gen
