replicaCount: 1

image:
  repository: ghcr.io/kevinpthorne/p2p-vpn
  pullPolicy: IfNotPresent
  tag: "latest"

frr:
  image:
    repository: quay.io/frrouting/frr
    pullPolicy: IfNotPresent
    tag: "9.1.0"

p2pVpn:
  dataKeySecretName: "p2p-vpn"
  dataKeySecretKey: "token"
  generateDataKey: false
  address: "10.255.255.1/24"  # Override per cluster
  p2pPort: 4001 # The internal container port for libp2p traffic
  isBootstrapPeer: false # Set to true to expose the p2pPort via a LoadBalancer Service
  # bootstrapPeers is an array of multiaddrs
  bootstrapPeers: []
  logLevel: "debug"
  cluster: "loa-vpn"
  identitySecretName: "p2p-vpn-identity"
  identitySecretKey: "identity.key"
  configMapName: "p2p-vpn-config"
  caConfigMapKey: "ca.pub"
  sigConfigMapKey: "node.sig"
  whitelistConfigMapKey: "whitelist.txt"

bgp:
  localAS: 65001 # Override with 65000 + clusterID
  ciliumPeerAS: 65000 # The AS of your local Cilium nodes
  routerId: "10.255.255.1" # Typically the p2p-vpn address without subnet mask
  
  # localCIDRs are the local cluster's subnets (e.g. Pod and Service CIDRs) 
  # to advertise to the remote p2p-vpn peers.
  localCIDRs: [] 
  
  # vpnPeers are the IPs of the other clusters' p2p-vpn gateways on the VPN subnet (e.g. 10.255.255.2)
  vpnPeers: []

persistence:
  enabled: true
  storageClass: ""
  size: 100Mi

nodeSelector: {}
tolerations: []
affinity: {}

networkPolicy:
  enabled: true

