apiVersion: v1
kind: Service
metadata:
  name: {{ include "allstarlink.fullname" . }}
  labels:
    {{- include "allstarlink.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpsPort }}
      targetPort: https
      protocol: TCP
      name: https
    - port: {{ .Values.service.iaxPort }}
      targetPort: iax
      protocol: UDP
      name: iax
    - port: {{ .Values.service.sipPort }}
      targetPort: sip
      protocol: UDP
      name: sip
  selector:
    {{- include "allstarlink.selectorLabels" . | nindent 4 }}
