argoNamespace: argo-cd
cluster: {}

pki:
  rootCAIssuer: app-pki-bootstrap-issuer  # currently implied to be ClusterIssuer
  certManagerNamespace: cert-manager

global:
  domain: "yourdomain.invalid"

kamailio:
  replicaCount: 2
  image: "ghcr.io/kamailio/kamailio-ci:6.0-alpine"
  ports:
    sip: 5060
    ws: 8080 # Internal port Kamailio listens on for WebSockets

rtpengine:
  # Deployed as a DaemonSet to maximize node coverage with hostNetwork
  image: "sipwise/rtpengine:latest"
  ports:
    min: 10000
    max: 20000
    control: 22222

asterisk:
  replicaCount: 1
  image: "andrius/asterisk:22"
  ports:
    sip: 5060