# Default values for allstarlink.
replicaCount: 1

image:
  repository: andrius/asterisk
  pullPolicy: IfNotPresent
  tag: "22"

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  httpsPort: 443
  iaxPort: 4569
  sipPort: 5060

tls:
  enabled: true
  secretName: allstarlink-tls

persistence:
  enabled: true
  storageClass: "longhorn"
  size: 5Gi

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 999
  runAsGroup: 999
  fsGroup: 999
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  runAsNonRoot: true
  runAsUser: 999

nodeSelector: {}

tolerations: []

affinity: {}
