apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kamailio
  labels:
    app: kamailio
spec:
  selector:
    matchLabels:
      app: kamailio
  template:
    metadata:
      labels:
        app: kamailio
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/kamailio/configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: kamailio
          image: {{ .Values.kamailio.image }}
          ports:
            - name: sip-udp
              containerPort: {{ .Values.kamailio.ports.sip }}
              protocol: UDP
            - name: sip-tcp
              containerPort: {{ .Values.kamailio.ports.sip }}
              protocol: TCP
            - name: ws-tcp
              containerPort: {{ .Values.kamailio.ports.ws }}
              protocol: TCP
          volumeMounts:
            - name: kamailio-config-volume
              mountPath: /etc/kamailio/kamailio.cfg
              subPath: kamailio.cfg
            - name: kamailio-config-volume
              mountPath: /etc/kamailio/tls.cfg
              subPath: tls.cfg
            - name: kamailio-tls-volume
              mountPath: /etc/kamailio/tls
              readOnly: true
            - name: kamailio-run
              mountPath: /run/kamailio
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: kamailio-config-volume
          configMap:
            name: kamailio-config
        - name: kamailio-tls-volume
          secret:
            secretName: {{ .Release.Name }}-kamailio-tls
        - name: kamailio-run
          emptyDir: {}