apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-kamailio-sip
  annotations:
    # Optional: Enable Cilium DSR to reduce latency on return packets
    service.cilium.io/global-service: "true"
    {{- if .Values.global.domain }}
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.global.domain | quote }}
    {{- end }}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local # Preserves the source IP of the caller
  ports:
    - name: sip-udp
      port: {{ .Values.kamailio.ports.sip }}
      protocol: UDP
    - name: sip-tcp
      port: {{ .Values.kamailio.ports.sip }}
      protocol: TCP
    - name: sip-wss
      port: 443
      targetPort: {{ .Values.kamailio.ports.ws }}
      protocol: TCP
  selector:
    app: kamailio