apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-kamailio-sip
  annotations:
    # Optional: Enable Cilium DSR to reduce latency on return packets
    service.cilium.io/global-service: "true" 
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local # Preserves the source IP of the caller
  ports:
    - name: sip-udp
      port: {{ .Values.kamailio.ports.sip }}
      protocol: UDP
    - name: sip-tcp
      port: {{ .Values.kamailio.ports.sip }}
      protocol: TCP
  selector:
    app: kamailio