apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-kamailio-ws
spec:
  type: ClusterIP
  ports:
    - name: ws-tcp
      port: {{ .Values.kamailio.ports.ws }}
      targetPort: ws-tcp
      protocol: TCP
  selector:
    app: kamailio
