apiVersion: keycloak.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: keycloak-provider-config
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true  # crossplane pkg CRD can lag
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: keycloak-creds
      key: credentials.json