apiVersion: db.loa.kevinpthorne.com/v1alpha1
kind: PrivateSchema
metadata:
  name: keycloak-schema
  namespace: keycloak
spec:
  crossplane:
    compositionRef:
      name: pgedge-private-schema
  databaseName: app
  schemaName: keycloak
  userName: keycloak